In [1]:
# LabelEncoder import
from sklearn.preprocessing import LabelEncoder
import numpy as np

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

# Encoding 모형을 Label Encoding으로 설정
encoder = 

# 학습 및 변환
labels = 

print(labels)

[0 1 4 5 3 2 2]


In [2]:
# 변환된 숫자(코드)에 대응되는 범주형 변수값 출력하기
print()

['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
# 숫자(코드)를 범주형 변수로 역변환
print()

['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '믹서' '믹서']


In [4]:
labels

array([0, 1, 4, 5, 3, 2, 2], dtype=int64)

In [5]:
# OneHotEncoder import
from sklearn.preprocessing import OneHotEncoder

# One-hot encoding을 준비하기 위해 열이 하나인 2차원 배열로 구조 변환
labels = 
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [2],
       [2]], dtype=int64)

In [6]:
# Encoding 모형을 One-hot encoding으로 설정
oh_encoder = 
oh_labels = 
print(oh_labels)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 2)	1.0
  (6, 2)	1.0


In [7]:
# Encoding 결과를 2차원 배열로 변환
print()

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
